#!/bin/bash

if ! source ./tools/env; then
    exit 1
fi

mkdir -p ./etc

if ! [ -f ./etc/sockd.conf ]; then
    cp ./etc-available/sockd.conf ./etc/sockd.conf
fi

if ! [ -f ./etc/users ]; then
    touch ./etc/users
fi

docker-compose up -d --build dante
