#!/bin/bash

[[ -z $DANTE_SERVICE_NAME ]] && echo "Error: Missing DANTE_SERVICE_NAME env variable" && exit 1

DANTE_CONTAINER_NAME="dante-$DANTE_SERVICE_NAME"
DANTE_VOLUME="dante-data-$DANTE_SERVICE_NAME"

docker run \
    --name $DANTE_CONTAINER_NAME \
    -v $DANTE_VOLUME:/etc/dante \
    --log-driver=none \
    -p 1080:1080 \
    -d \
    strelga/docker-dante:latest

echo "Run container $DANTE_CONTAINER_NAME with volume $DANTE_VOLUME"
