#!/bin/sh

[[ -z $SERVICE_NAME ]] && echo "Error: Missing SERVICE_NAME env variable" && exit 1

DANTE_DATA="dante-$SERVICE_NAME"
DANTE_CONTAINER_NAME="dante-data-$SERVICE_NAME"

docker volume create --name $DANTE_DATA
docker run -v $DANTE_DATA:/etc/openvpn -t $DANTE_CONTAINER_NAME --log-driver=none --rm strelga/docker-dante
